title: Swiss cheese
theme_color: green-light # options: yellow, orange, green, teal, purple, black
#theme_style: light # options: dark or light (for background)
syntax_highlighting: light # light or dark (solarized color scheme)
gradient_header: false

author: Baird
email: langenbrunner@gmail.com
timezone: America/Los_Angeles

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:  heyitsbaird
github_username:  bairdlangenbrunner
linkedin_username:  bairdlangenbrunner


plugins:
  - jekyll-feed
  - jemoji

# this will make sure pages get navbar placement
include:
  - _pages

# note:  pages and posts are core collections!
collections:
  - writing

collections:
  writing:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: writing
    values:
      layout: post-nodate
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page

collections_dir: collections

# Build settings
markdown: kramdown
highlighter: rouge
