title: Baird's Swiss Theme
description: A revised version of the Swiss Jekyll theme
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: bairdlangenbrunner # the GitHub repo name for your project
github_username: bairdlangenbrunner

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: jekyllrb

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: solarized-teal

# Build settings
markdown: kramdown
highlighter: rouge

author: Baird
email: langenbrunner@gmail.com